version: "3.8"
   
services:
  filestoragedb:
    env_file: .env
    image: bitnami/postgresql:13
    volumes:
      - filestoragedb:/var/lib/postgresql/data
    container_name: filestoragedb
    ports:
      - 5432:5432

  web:
    build: .
    command: ./docker-entrypoint.sh
    restart: unless-stopped
    volumes:
      - .:/src
    ports:
      - 8000:8000
    env_file: .env
    depends_on:
      - filestoragedb

volumes:
  filestoragedb:
    external: false